site_name: Campus Study Buddy Docs
site_url: https://gimbiyasa.github.io/campus_study_buddy/
repo_url: https://github.com/GimbiyaSa/campus_study_buddy
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: teal
      accent: teal
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
plugins:
  - search
  - mermaid2

nav:
  - Home: index.md
  - Overview:
      - Overview: overview/index.md
      - Roadmap: overview/roadmap.md
  - Frontend:
      - Overview: frontend/index.md
      - Pages & Layout: frontend/pages.md
      - Components: frontend/components.md
      - State management: frontend/state-management.md
  - Backend:
      - Overview: backend/index.md
      - API: backend/api.md
      - Data models: backend/data-models.md
      - Services: backend/services.md
  - Architecture:
      - Overview: architecture/index.md
      - Diagrams: architecture/diagrams.md
  - Infrastructure:
      - Overview: infrastructure/index.md
      - Environments: infrastructure/environments.md
      - CI/CD: infrastructure/ci-cd.md
  - Design System:
      - Overview: design-system/index.md
      - Tokens: design-system/tokens.md
      - Accessibility: design-system/accessibility.md
  - Operations:
      - Overview: operations/index.md
      - Runbooks: operations/runbooks.md
      - Troubleshooting: operations/troubleshooting.md
