title: "Study Buddy Campus API Documentation"
description: "Comprehensive REST API documentation for student collaboration platform"
url: "https://gimbiyasa.github.io"
baseurl: "/campus_study_buddy"
author: "Study Buddy Team"
repository: "GimbiyaSa/campus_study_buddy"
github_username: "GimbiyaSa" 

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - setup.sh
  - node_modules/
  - vendor/

include:
  - _pages
  - assets
